#!/bin/sh

# Add .scripts and all subdirectories to $PATH
if [ -d $HOME/.dotfiles/scripts/ ] ; then
    export PATH="$PATH:$(du "$HOME/.dotfiles/scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
fi

# Add Projects/scripts and all subdirectories to $PATH
if [ -d $HOME/Projects/scripts/ ] ; then
    export PATH="$PATH:$(du "$HOME/Projects/scripts/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
fi

# Add local bin folder to path
export PATH="$PATH:$HOME/.local/bin"

# Set default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="ranger"

# Start X11 server if i3 is not already running
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x i3 >/dev/null && exec startx

# Load bashrc
echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && source "$HOME/.bashrc"
