#!/bin/sh

# Set default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="lf"

# Start X11 server if i3 is not already running
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x i3 >/dev/null && exec startx

# lf
LFCD="$GOPATH/src/github.com/gokcehan/lf/etc/lfcd.sh"
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

# Go
export GOPATH="${HOME}/.go"
export PATH="$PATH:${GOPATH}/bin"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Ruby
if which ruby &>/dev/null && which gem &>/dev/null; then
    export PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi

# Dotfiles scripts
if [ -d "${HOME}/.dotfiles/scripts" ] ; then
    export PATH="$PATH:${HOME}/.dotfiles/scripts"
fi

# Local binaries
if [ -d "${HOME}/.local/bin" ] ; then
    export PATH="$PATH:${HOME}/.local/bin"
fi

# Load bashrc
echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && . "${HOME}/.bashrc"
