#!/bin/sh

# Function to add subdirectories to PATH
addSubdirsToPath() {
    DIR="${1}"
    DIRS="$(du "${DIR}" | grep -v "/.git" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"
    export PATH="${PATH}:${DIRS}"
}

# Add .scripts and all subdirectories to $PATH
addSubdirsToPath "${HOME}/.dotfiles/scripts/"

# Add Projects/scripts and all subdirectories to $PATH
addSubdirsToPath "${HOME}/Projects/scripts/"

# Add local bin folder to path
export PATH="${PATH}:${HOME}/.local/bin"

# Set default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export READER="zathura"
export FILE="ranger"

# Start X11 server if i3 is not already running
[ "$(tty)" = "/dev/tty1" ] && ! pgrep -x i3 >/dev/null && exec startx

# Load bashrc
echo "$0" | grep "bash$" >/dev/null && [ -f ~/.bashrc ] && source "${HOME}/.bashrc"
