# Disable ctrl-s and ctrl-q
stty -ixon

# Allow to cd into a directory by typing the directory name
shopt -s autocd

# Infinite history
HISTSIZE= HISTFILESIZE=

# Prompt
export PS1="\[$(tput bold)\]\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 1)\]\W \[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"

# Setup aliases
source ~/.aliases

# FZF
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
bind -x '"\C-e": fzf | xargs $EDITOR;'

# Pipenv
export PIPENV_VENV_IN_PROJECT=1
